#postgres
services:
  db:
    image: postgres:14.2-alpine
    container_name: demo-postgres-14.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: 
      "postgres -c 'max_connections=500'"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    profiles: 
      - front-dev
      - prod
  backend:
    image: style12341/gestor-aulas:latest
    command: "./bin/rails server"
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=1
    volumes:
      - app-storage:/rails/storage
      - ./public/files:/rails/public/files
    depends_on:
      - db
    ports:
      - "3000:3000"
    profiles: 
      - front-dev
      - prod
  frontend:
    image: style12341/gestor-aulas-front:latest
    command: "npm run dev"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
    ports:
      - "8080:8080"
    profiles:
      - back-dev
      - prod

volumes:
  postgres_data: {}
  app-storage: {}